<section class="card">
    <div class="card-body card-cta">
        <div class="flex-grow">
            <h2 class="heading">Backup codes</h2>
            <div class="description">
                After logging in, you will be required to enter a security code. Security codes will be generated by your preferred authenticator app.
            </div>
        </div>
        <div class="flex-shrink">
            <x-button wire:click="submit">
                View codes
            </x-button>
        </div>
    </div>
</section>
