<div class="flex flex-col divide-y dark:divide-gray-700">
    <div class="p-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            Two factor authentication
        </h1>
        @if (session('status'))
            <div class="mb-4 font-medium text-sm text-green-600">
                {{ session('status') }}
            </div>
        @endif
        <div class="font-light text-gray-500 dark:text-gray-400 mt-4">
            We recommend using Google Authenticator, 1Password or Authy.
            Once your authenticator app is installed,
            scan the QR-code below and enter the security code
            generated by your authenticator app.
        </div>
        <div class="flex items-center justify-center mt-6">
            {!! auth()->user()->twoFactorQrCodeSvg() !!}
        </div>
    </div>
    <div class="p-6 sm:p-8">
        <label for="password" class="label">
            Security code
        </label>
        <input wire:model="code" type="text" class="bg-gray-50 border border-gray-300 text-center text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        @error('code')
            <div class="mt-1 text-xs text-red-600 dark:text-red-500">{{ $message }}</div>
        @enderror
    </div>
    <div class="flex items-center justify-evenly gap-4 p-6 sm:p-8">
        <button wire:click="submit" class="btn-blue w-full">
            Verify code
        </button>
        <a href="{{ route('profile.password') }}" class="btn-default w-full">
            Abort
        </a>
    </div>
</div>
