@extends('layouts.app')

@section('breadcrumbs')
    <x-breadcrumbs-item>
        My account
    </x-breadcrumbs-item>
    <x-breadcrumbs-item url="{{ route('profile.password') }}">
        Security
    </x-breadcrumbs-item>
@endsection

@section('content')
    @if (session('status') == 'two-factor-authentication-confirmed')
        <div class="">
            two-factor-authentication-confirmed
        </div>
    @endif
    <div class="flex items-center justify-between mb-8">
        <h1 class="title">Security</h1>
    </div>
    <div class="space-y-8">
        @livewire('profile-password-form')
        @livewire('profile-two-factor-form')
        @if (auth()->user()->hasEnabledTwoFactorAuthentication())
            <section class="card">
                <div class="card-body card-cta">
                    <div class="flex-grow">
                        <h2 class="heading">Backup codes</h2>
                        <div class="description">
                            After logging in, you will be required to enter a security
                            code. Security codes will be generated by your preferred
                            authenticator app.
                        </div>
                    </div>
                    <div class="flex-shrink">
                        <a href="{{ route('profile.two-factor.codes') }}" class="btn-blue">
                            View codes
                        </a>
                    </div>
                </div>
            </section>
        @endif
    </div>
@endsection
